apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-label
  template:
    metadata:
      labels:
        app: client-label
    spec:
      containers:
        - name: client-container
          image: client-image
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client-label
  type: ClusterIP
  ports:
    - containerPort: 80
