apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-label
  template:
    metadata:
      labels:
        app: gateway-label
    spec:
      containers:
        - name: gateway-container
          image: gateway-image
          env:
            - name: APP_PORT
              value: 80
            - name: nats_url
              value: nats:4222
            - name: ACCESS_TOKEN_SECRET
              value: secretKey
            - name: SIGNED_COOKIE_SECRET
              value: secretKey
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway-label
  type: ClusterIP
  ports:
    - containerPort: 80
