apiVersion: apps/v1
kind: Deployment
metadata:
  name: like-count-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: like-count-label
  template:
    metadata:
      labels:
        app: like-count-label
    spec:
      containers:
        - name: like-count-container
          image: like-count-image
          env:
            - name: APP_PORT
              value: 80
            - name: nats_url
              value: nats:4222
            - name: mongo_url
              value: mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: like-count
spec:
  selector:
    app: like-count-label
  type: ClusterIP
  ports:
    - containerPort: 80
