apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-label
  template:
    metadata:
      labels:
        app: post-label
    spec:
      containers:
        - name: post-container
          image: post-image
          env:
            - name: APP_PORT
              value: 80
            - name: nats_url
              value: nats:4222
            - name: mongo_url
              value: mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: post
spec:
  selector:
    app: post-label
  type: ClusterIP
  ports:
    - containerPort: 80
