apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-label
  template:
    metadata:
      labels:
        app: recommendation-label
    spec:
      containers:
        - name: recommendation-container
          image: recommendation-image
          env:
            - name: APP_PORT
              value: 80
            - name: mongo_url
              value: mongo:27017
            - name: redis_url
              value: redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  selector:
    app: recommendation-label
  type: ClusterIP
  ports:
    - containerPort: 80
