apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-graph-view-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-graph-view-label
  template:
    metadata:
      labels:
        app: user-graph-view-label
    spec:
      containers:
        - name: user-graph-view-container
          image: user-graph-view-image
          env:
            - name: APP_PORT
              value: 80
            - name: mongo_url
              value: mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: user-graph-view
spec:
  selector:
    app: user-graph-view-label
  type: ClusterIP
  ports:
    - containerPort: 80
