# values of common environment variables
APP_PORT: 80
nats_url: nats:4222
mongo_url: mongo:27017
redis_url: redis:6379




services:

  - serviceName: auth
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true
    secret_env:
      - secretName: auth-secret
        key:  ACCESS_TOKEN_SECRET
      - secretName: auth-secret
        key:  SIGNED_COOKIE_SECRET

  - serviceName: client
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 

  - serviceName: comment
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true

  - serviceName: feed
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true
      redis_url: true
    extra_env:
      - name: userGraphView_url
        value: user-graph-view:80

  - serviceName: gateway
    replicaCount: 1
    serviceType: LoadBalancer
    env: 
      APP_PORT: true 
      nats_url: true
    secret_env:
      - secretName: auth-secret
        key:  ACCESS_TOKEN_SECRET
      - secretName: auth-secret
        key:  SIGNED_COOKIE_SECRET

  - serviceName: like
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true
      redis_url: true

  - serviceName: like-batch-updater
    replicaCount: 1
    env: 
      nats_url: true
      mongo_url: true

  - serviceName: like-count
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true

  - serviceName: like-updater
    replicaCount: 1
    env: 
      nats_url: true
      mongo_url: true
      redis_url: true

  - serviceName: post
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true

  - serviceName: recommendation
    replicaCount: 1
    env: 
      mongo_url: true
      redis_url: true

  - serviceName: spotify
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true
      redis_url: true
    secret_env:
      - secretName: spotify-secret
        key:  SPOTIFY_CLIENT_KEY
      - secretName: spotify-secret
        key:  SPOTIFY_CLIENT_SECRET

  - serviceName: user
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true
    secret_env:
      - secretName: aws-secret
        key:  AWS_ACCESS_KEY_ID
      - secretName: aws-secret
        key:  AWS_SECRET_ACCESS_KEY

  - serviceName: user-graph
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      nats_url: true
      mongo_url: true

  - serviceName: user-graph-view
    replicaCount: 1
    serviceType: ClusterIP
    env: 
      APP_PORT: true 
      mongo_url: true

  - serviceName: mongo
    image: mongo:6.0.3
    replicaCount: 1
    memory: "800Mi"
    cpu: "800m"
    volumes:
      - name: mongo-storage
        claimName: mongo-pvc
        mountPath: /data/db
      - name: init-mongo-configmap
        mountPath: /docker-entrypoint-initdb.d/init-repl.js
        subPath: init-repl.js
        configMap:
          name: init-mongo-configmap
      - name: wired-tiger-config
        mountPath: /etc/mongod.conf
        subPath: mongod.conf
        configMap:
          name: wired-tiger-config
    serviceType: ClusterIP
    servicePort: 27017
    extra_env:
      - name: ALLOW_EMPTY_PASSWORD
        value: yes
    command:
      - /usr/local/bin/docker-entrypoint.sh
      - "mongod"
      # bug
      - "-f/etc/mongod.conf"

  - serviceName: nats
    image: nats:2.9.6-alpine3.16
    replicaCount: 1
    volumes:
      - name: nats-storage
        claimName: nats-pvc
        mountPath: /tmp/nats/jetstream
    serviceType: ClusterIP
    servicePort: 4222
    command:
      - /usr/local/bin/docker-entrypoint.sh
      - nats-server
      - "-js"


  - serviceName: redis
    image: redis:7.0.5-alpine3.16
    replicaCount: 1
    volumes:
      - name: redis-storage
        claimName: redis-pvc
        mountPath: /data
    serviceType: ClusterIP
    servicePort: 6379
    command:
      - /usr/local/bin/docker-entrypoint.sh
      - redis-server
      - "--save 60 1"
      - "--loglevel warning"

