import Head from "next/head";

import Sidebar from "./Sidebar"
import Widgets from "./Widgets"


const Layout = ({Children, ...props}) => {

    return (
        <div>
            <Head>
                <title>Rhime</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex min-h-screen">
                {/* Sidebar */}
                <Sidebar {...props}/>

                {/* Feed */}

                <Children {...props}/>

                {/* Widgets */}

                <Widgets {...props} />

                

            </main>
        </div>
    )
}

export default Layout