
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: azurefile-csi
#   volumeName: mongo-pv
#   resources:
#     requests:
#       storage: 3Gi

# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: nats-pv
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inmemory-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: inmemory-pv
  resources:
    requests:
      storage: 3Gi
